---
name: Continuous Integration

"on":
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  targets:
    name: Enumerate Just recipes
    runs-on: warp-ubuntu-latest-x64-2x

    permissions:
      contents: read # Checkout code

    outputs:
      matrix: ${{ steps.export-targets.outputs.targets }}

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Install Just
        uses: taiki-e/install-action@5bf6ce016fd2e72eefc647cbca1e4213f65955b8 # v2.87.5
        with:
          tool: just

      - name: Export targets
        id: export-targets
        run: echo "targets=$(just --list | awk '/check-|format-|lint-|test-/{print $1}' | jq -cnR '[inputs]')" >> "$GITHUB_OUTPUT"

  checks:
    name: ${{ matrix.target }}
    runs-on: warp-ubuntu-latest-x64-2x

    permissions:
      contents: read # Checkout code

    needs: targets

    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.targets.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Install Flox
        uses: flox/install-flox-action@1128abd73431089ab9d871c893b4e72a729354e1 # v2.6.0
        with:
          # renovate: datasource=github-releases depName=flox/flox
          version: 1.15.0

      - name: Remove Flox installer (if it exists)
        run: rm -f flox.x86_64-linux.deb

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          prefix-key: "v0-${{ matrix.target }}"
          cache-on-failure: true
          cache-provider: "warpbuild"

      - name: Run check with Just
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1.1.1
        with:
          command: just ${{ matrix.target }}

  success:
    name: All checks succeeded
    runs-on: warp-ubuntu-latest-x64-2x

    permissions: {}

    needs: checks
    if: always()

    steps:
      - name: Check if all checks succeeded
        # `needs` is a list of job names, which themselves are generated from
        # the output of `just --list`, so we ignore the template injection here.
        # zizmor: ignore[template-injection]
        run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
